<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapaDominio\ProyectoOdontologia.Domain.csproj" />
    <ProjectReference Include="..\CapaAplicacion\ProyectoOdontologia.Application.csproj" />
    <ProjectReference Include="..\CapaInfraestructura\ProyectoOdontologia.Infrastructure.csproj" />
  </ItemGroup>

</Project>